version: '3.9'

services:
  nginx-proxy-manager:
    image: 'docker.io/jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    container_name: nginx-proxy-manager
    network_mode: host
    environment:
      - DISABLE_IPV6=true
    volumes:
      - ./npm/data:/data
      - ./npm/letsencrypt:/etc/letsencrypt

  nextcloud-aio-mastercontainer:
    image: ghcr.io/nextcloud-releases/all-in-one:latest
    init: true
    restart: always
    container_name: nextcloud-aio-mastercontainer
    volumes:
      - nextcloud_aio_mastercontainer:/mnt/docker-aio-config
      - /var/run/docker.sock:/var/run/docker.sock:ro
    network_mode: bridge
    ports:
      - 8080:8080
    # security_opt: ["label:disable"] # Needed if using SELinux
    environment:
      APACHE_PORT: 11000
      FULLTEXTSEARCH_JAVA_OPTIONS: "-Xms1024M -Xmx1024M"
      NEXTCLOUD_DATADIR: /bestanden/data
      NEXTCLOUD_UPLOAD_LIMIT: 4G
      NEXTCLOUD_MAX_TIME: 3600
      NEXTCLOUD_MEMORY_LIMIT: 1028M
      SKIP_DOMAIN_VALIDATION: false
      # Uncomment and adjust any of these if needed:
      # AIO_DISABLE_BACKUP_SECTION: false
      # APACHE_IP_BINDING: 127.0.0.1
      # APACHE_ADDITIONAL_NETWORK: frontend_net
      # BORG_RETENTION_POLICY: --keep-within=7d --keep-weekly=4 --keep-monthly=6
      # COLLABORA_SECCOMP_DISABLED: false
      # DOCKER_API_VERSION: 1.44
      # NEXTCLOUD_MOUNT: /mnt/
      # NEXTCLOUD_TRUSTED_CACERTS_DIR: /path/to/my/cacerts
      # NEXTCLOUD_STARTUP_APPS:
      # NEXTCLOUD_ADDITIONAL_PHP_EXTENSIONS: imagick
      # NEXTCLOUD_ENABLE_DRI_DEVICE: true
      # NEXTCLOUD_ENABLE_NVIDIA_GPU: true
      # NEXTCLOUD_KEEP_DISABLED_APPS: false
      # TALK_PORT: 3478
      # WATCHTOWER_DOCKER_SOCKET_PATH: /var/run/docker.sock

# Optional: uncomment Caddy or other reverse proxies if needed
# caddy:
#   image: caddy:alpine
#   restart: always
#   container_name: caddy
#   volumes:
#     - caddy_certs:/certs
#     - caddy_config:/config
#     - caddy_data:/data
#     - caddy_sites:/srv
#   network_mode: "host"
#   configs:
#     - source: Caddyfile
#       target: /etc/caddy/Caddyfile

volumes:
  nextcloud_aio_mastercontainer:
  # caddy_certs:
  # caddy_config:
  # caddy_data:
